#!/bin/bash
load rbenv into shell session
if [ -d "$OPENSHIFT_DATA_DIR/.rbenv" ]; then
  export RUBY_VERSION=2.1.3
  export RBENV_ROOT=$OPENSHIFT_DATA_DIR/.rbenv
  export PATH="$RBENV_ROOT/bin:$PATH"
  eval "$(rbenv init -)"
fi
